### ISSUE TITLE
400 Client Error: Bad Request for url: http://api.deepgram.com/

### ISSUE THREAD

**Issue by toofan0909** [agouil/deepgram-python#1]
I would really appreciate if you could create bit more documentation around deepgram

for example 
step 1, create db object
step 2, upload a media (mp3/mp4/wav) file to dg
step 3, retrieve the text for the file
step 4, update the conversation 

at the moment i am getting following error

[ERROR]: 2017-10-27 10:36:16,286 [C:\Python27\lib\site-packages\deepgram\deepgra
m.py:40] 400 Client Error: Bad Request for url: http://api.deepgram.com/
Traceback (most recent call last):
  File "wit_test.py", line 23, in <module>
    print dg.check_balance()
  File "C:\Python27\lib\site-packages\deepgram\deepgram.py", line 53, in check_b
alance
    return self._make_request(data)
  File "C:\Python27\lib\site-packages\deepgram\deepgram.py", line 38, in _make_r
equest
    headers=self._get_headers(), params=data)
  File "C:\Python27\lib\site-packages\deepgram\http.py", line 81, in post
    return self._parse_response(response, format)
  File "C:\Python27\lib\site-packages\deepgram\http.py", line 34, in _parse_resp
onse
    response.raise_for_status()
  File "C:\Python27\lib\site-packages\requests\models.py", line 862, in raise_fo
r_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://api
.deepgram.com/

**Comment by agouil** [comment]
The deepgram API has been permanently moved to brain.deepgram.com. I'm planning to update the package over the next weeks to work with the new endpoint.
In the meantime, if you would like to make the changes and send a pull request, I'm happy to accept it.

**Comment by toofan0909** [comment]
def __init__(self, api_key):
        """
        Class constructor.

        Params:
            api_key (string): The API Key
        """

        self.api_key = api_key
        self.logger = logger()
        #self.client = Http('http://api.deepgram.com')
        self.client = Http('https://brain.deepgram.com')     #even this is not working

**Comment by agouil** [comment]
Deepgram have issued their own Python wrapper for the new API version, here: https://github.com/deepgram/deepgram-brain-python. It's build for Python 3. Maybe give this a try instead?

**Comment by toofan0909** [comment]
currently working with that only ,, but that's in on python 3.. which I dislike for portability reasons ./...
